server:
  port: 8080
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.18.0"
      repository: "https://maven.lavalink.dev/releases"

  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      soundcloud: true
      http: true

    youtube:
      enabled: true
      allowSearch: true
      allowDirectVideoIds: true

logging:
  level:
    root: INFO
    lavalink: INFO
