server:
  port: 8080
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"

    sources:
      youtube: false
      soundcloud: true
      http: true

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true

logging:
  level:
    root: INFO
    lavalink: INFO
